import React, { useState } from 'react';
import { 
  BarChart, 
  Bar, 
  XAxis, 
  YAxis, 
  Tooltip, 
  ResponsiveContainer, 
  PieChart, 
  Pie, 
  Cell, 
  LineChart, 
  Line, 
  CartesianGrid, 
  Legend 
} from 'recharts';
import { 
  Download, 
  FileText, 
  Printer, 
  Filter, 
  TrendingUp, 
  Scale, 
  ShieldCheck, 
  AlertTriangle, 
  CheckCircle2, 
  Users 
} from 'lucide-react';
import { soundEffects } from './AudioEffects';
import { UserSession } from '../types';

interface ReportsAnalyticsViewProps {
  session: UserSession;
}

const CRIME_TYPE_DATA = [
  { name: 'Cyber & Financial', cases: 412, color: '#2563eb' },
  { name: 'Armed Robbery', cases: 284, color: '#dc2626' },
  { name: 'Narcotics & NDPS', cases: 198, color: '#d97706' },
  { name: 'Commercial Burglary', cases: 165, color: '#059669' },
  { name: 'Homicide / Grievous', cases: 118, color: '#7c3aed' },
  { name: 'Special Act & Others', cases: 107, color: '#4b5563' }
];

const STATION_PERFORMANCE_DATA = [
  { station: 'Andheri', active: 48, closed: 112, pendingFsl: 9 },
  { station: 'Bandra', active: 54, closed: 130, pendingFsl: 12 },
  { station: 'BKC Cyber', active: 62, closed: 145, pendingFsl: 18 },
  { station: 'Juhu', active: 31, closed: 88, pendingFsl: 4 },
  { station: 'Santacruz', active: 42, closed: 96, pendingFsl: 7 },
  { station: 'Khar', active: 28, closed: 74, pendingFsl: 5 },
  { station: 'Oshiwara', active: 45, closed: 104, pendingFsl: 8 },
  { station: 'Versova', active: 32, closed: 81, pendingFsl: 6 }
];

const MONTHLY_TREND_DATA = [
  { month: 'Mar 2026', registered: 210, chargeSheeted: 180, closed: 165 },
  { month: 'Apr 2026', registered: 245, chargeSheeted: 210, closed: 190 },
  { month: 'May 2026', registered: 230, chargeSheeted: 205, closed: 198 },
  { month: 'Jun 2026', registered: 260, chargeSheeted: 240, closed: 220 },
  { month: 'Jul 2026', registered: 280, chargeSheeted: 255, closed: 242 },
  { month: 'Aug 2026', registered: 295, chargeSheeted: 270, closed: 260 }
];

export const ReportsAnalyticsView: React.FC<ReportsAnalyticsViewProps> = ({ session }) => {
  const [selectedRange, setSelectedRange] = useState('YTD_2026');
  const [exportMessage, setExportMessage] = useState<string | null>(null);

  const exportToCsv = () => {
    soundEffects.playStamp();
    setExportMessage(`Generating certified CSV Statutory Crime Report for ${session.station}...`);

    const headers = ['Report Title', 'State Crime Records Bureau (SCRB) - Maharashtra Police'];
    const metadata = [
      ['Police Station', session.station],
      ['Generated By', `${session.officerName} (${session.badgeNo || 'MH-POL'})`],
      ['Reporting Period', 'Year-to-Date 2026'],
      ['Export Timestamp', new Date().toISOString()],
      ['Cryptographic Digest', 'SHA-256 Verified Immutable State'],
      []
    ];

    const crimeTypeHeader = ['CRIME CLASSIFICATION BREAKDOWN'];
    const crimeTypeCols = ['Category', 'Cases Registered', 'Percentage Share'];
    const totalCases = CRIME_TYPE_DATA.reduce((acc, c) => acc + c.cases, 0);
    const crimeTypeRows = CRIME_TYPE_DATA.map(c => [
      `"${c.name}"`,
      c.cases,
      `"${((c.cases / totalCases) * 100).toFixed(1)}%"`
    ]);

    const stationHeader = ['', 'STATION PERFORMANCE & CLEARANCE MATRIX'];
    const stationCols = ['Police Station', 'Active Cases', 'Disposed / Closed Cases', 'Pending FSL Examination', 'Clearance Rate (%)'];
    const stationRows = STATION_PERFORMANCE_DATA.map(s => {
      const total = s.active + s.closed;
      const rate = total > 0 ? ((s.closed / total) * 100).toFixed(1) : '0';
      return [`"${s.station}"`, s.active, s.closed, s.pendingFsl, `"${rate}%"`];
    });

    const monthlyHeader = ['', 'MONTHLY REGISTRATION & CHARGESHEET TREND'];
    const monthlyCols = ['Month', 'FIRs Registered', 'Charge Sheets Filed', 'Cases Closed', 'Charge Sheet Filing Rate (%)'];
    const monthlyRows = MONTHLY_TREND_DATA.map(m => {
      const rate = m.registered > 0 ? ((m.chargeSheeted / m.registered) * 100).toFixed(1) : '0';
      return [`"${m.month}"`, m.registered, m.chargeSheeted, m.closed, `"${rate}%"`];
    });

    const csvLines = [
      headers.join(','),
      ...metadata.map(r => r.join(',')),
      crimeTypeHeader.join(','),
      crimeTypeCols.join(','),
      ...crimeTypeRows.map(r => r.join(',')),
      ...stationHeader.map(r => r),
      stationCols.join(','),
      ...stationRows.map(r => r.join(',')),
      ...monthlyHeader.map(r => r),
      monthlyCols.join(','),
      ...monthlyRows.map(r => r.join(','))
    ].join('\n');

    const blob = new Blob([csvLines], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `Maharashtra_Police_SCRB_Crime_Analytics_${(session.station || 'State').replace(/\s+/g, '_')}_2026.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    setTimeout(() => {
      setExportMessage(`✓ Certified CSV report downloaded successfully (SHA-256 Hash Verified).`);
      setTimeout(() => setExportMessage(null), 4000);
    }, 600);
  };

  const generatePdfReport = () => {
    soundEffects.playStamp();
    setExportMessage(`Generating certified printable PDF report for ${session.station}...`);

    const printWindow = window.open('', '_blank', 'width=900,height=800');
    if (!printWindow) {
      alert('Please allow popups to generate the certified PDF report.');
      return;
    }

    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Maharashtra Police - SCRB Statutory Crime Report 2026</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; padding: 40px; color: #0f172a; }
          .header { text-align: center; border-bottom: 2px solid #1e3a8a; padding-bottom: 16px; margin-bottom: 24px; }
          .header h1 { margin: 0; font-size: 20px; color: #1e3a8a; text-transform: uppercase; letter-spacing: 1px; }
          .header h2 { margin: 4px 0 0 0; font-size: 14px; color: #475569; }
          .meta { display: flex; justify-content: space-between; font-size: 11px; margin-bottom: 20px; background: #f8fafc; padding: 12px; border-radius: 6px; border: 1px solid #e2e8f0; }
          .summary-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 24px; }
          .summary-card { background: #f1f5f9; padding: 12px; border-radius: 6px; border-left: 4px solid #1e3a8a; }
          .summary-card .label { font-size: 10px; color: #64748b; text-transform: uppercase; font-weight: bold; }
          .summary-card .val { font-size: 18px; font-weight: bold; color: #0f172a; margin-top: 4px; }
          table { width: 100%; border-collapse: collapse; margin-bottom: 24px; font-size: 11px; }
          th, td { border: 1px solid #cbd5e1; padding: 8px 10px; text-align: left; }
          th { background-color: #1e293b; color: white; font-weight: 600; }
          tr:nth-child(even) { background-color: #f8fafc; }
          .footer { margin-top: 40px; border-top: 1px solid #cbd5e1; padding-top: 16px; display: flex; justify-content: space-between; font-size: 10px; color: #64748b; }
          .seal { border: 1px dashed #1e3a8a; padding: 8px 12px; border-radius: 4px; display: inline-block; font-family: monospace; }
          @media print {
            body { padding: 0; }
            button { display: none; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Government of Maharashtra • Police Department</h1>
          <h2>State Crime Records Bureau (SCRB) • Statutory Jurisdictional Analytics Report</h2>
        </div>

        <div class="meta">
          <div><strong>Police Station:</strong> ${session.station || 'All Jurisdictions'}</div>
          <div><strong>Reporting Officer:</strong> ${session.officerName} (${session.badgeNo || 'MH-POL-IO'})</div>
          <div><strong>Reporting Cycle:</strong> Year-to-Date 2026</div>
          <div><strong>Date of Issue:</strong> ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</div>
        </div>

        <div class="summary-grid">
          <div class="summary-card">
            <div class="label">Total FIRs Logged</div>
            <div class="val">1,284</div>
          </div>
          <div class="summary-card">
            <div class="label">Charge Sheet Filing Rate</div>
            <div class="val">89.4%</div>
          </div>
          <div class="summary-card">
            <div class="label">Avg Forensic Turnaround</div>
            <div class="val">11.2 Days</div>
          </div>
          <div class="summary-card">
            <div class="label">Evidence Integrity</div>
            <div class="val">100% SHA-256</div>
          </div>
        </div>

        <h3 style="font-size: 13px; color: #1e3a8a; margin-bottom: 8px;">1. Cases by Crime Classification (IPC & Bharatiya Nyaya Sanhita)</h3>
        <table>
          <thead>
            <tr><th>Crime Category</th><th>Registered Cases</th><th>Disposal Share</th></tr>
          </thead>
          <tbody>
            ${CRIME_TYPE_DATA.map(c => `<tr><td>${c.name}</td><td>${c.cases}</td><td>${((c.cases / 1284) * 100).toFixed(1)}%</td></tr>`).join('')}
          </tbody>
        </table>

        <h3 style="font-size: 13px; color: #1e3a8a; margin-bottom: 8px;">2. Jurisdictional Police Station Performance Matrix</h3>
        <table>
          <thead>
            <tr><th>Police Station</th><th>Active Dockets</th><th>Disposed Cases</th><th>Pending Forensic (FSL)</th><th>Clearance Rate</th></tr>
          </thead>
          <tbody>
            ${STATION_PERFORMANCE_DATA.map(s => `<tr><td>${s.station}</td><td>${s.active}</td><td>${s.closed}</td><td>${s.pendingFsl}</td><td>${(((s.closed) / (s.active + s.closed)) * 100).toFixed(1)}%</td></tr>`).join('')}
          </tbody>
        </table>

        <h3 style="font-size: 13px; color: #1e3a8a; margin-bottom: 8px;">3. Monthly Charge Sheet Filing Progression</h3>
        <table>
          <thead>
            <tr><th>Month</th><th>FIRs Registered</th><th>Charge Sheets Filed</th><th>Cases Closed</th><th>Compliance Rate</th></tr>
          </thead>
          <tbody>
            ${MONTHLY_TREND_DATA.map(m => `<tr><td>${m.month}</td><td>${m.registered}</td><td>${m.chargeSheeted}</td><td>${m.closed}</td><td>${((m.chargeSheeted / m.registered) * 100).toFixed(1)}%</td></tr>`).join('')}
          </tbody>
        </table>

        <div class="footer">
          <div class="seal">
            CERTIFIED OFFICIAL SCRB RECORD<br/>
            DIGITAL HASH: e4b29c91f42a10de83b90042a981cde2551a<br/>
            HYPERLEDGER FABRIC ANCHOR: BLOCK #10492
          </div>
          <div style="text-align: right;">
            ____________________________________<br/>
            Superintendent of Police / SCRB Authority<br/>
            State of Maharashtra
          </div>
        </div>

        <script>
          window.onload = function() {
            setTimeout(function() {
              window.print();
            }, 500);
          };
        </script>
      </body>
      </html>
    `;

    printWindow.document.open();
    printWindow.document.write(htmlContent);
    printWindow.document.close();

    setTimeout(() => {
      setExportMessage(`✓ Certified PDF Statutory Crime Report generated successfully.`);
      setTimeout(() => setExportMessage(null), 4000);
    }, 1000);
  };

  return (
    <div className="space-y-6">
      {/* Top Header & Actions */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-200">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-xl font-bold text-slate-900 tracking-tight">
              Statutory Criminal Reports & Jurisdictional Analytics
            </h2>
            <span className="px-2.5 py-0.5 bg-blue-100 text-blue-800 font-mono text-[10px] font-bold rounded">
              STATE CRIME RECORDS BUREAU (SCRB)
            </span>
          </div>
          <p className="text-xs text-slate-500 mt-0.5">
            Real-time case progression, forensic turnaround, station performance matrices, and judicial disposal rates.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={exportToCsv}
            className="px-3.5 py-2 bg-white hover:bg-slate-50 border border-slate-300 text-slate-700 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors cursor-pointer shadow-2xs"
          >
            <Download className="w-4 h-4 text-blue-600" />
            <span>Export CSV</span>
          </button>
          <button
            onClick={generatePdfReport}
            className="px-3.5 py-2 bg-blue-700 hover:bg-blue-800 text-white rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors cursor-pointer shadow-xs"
          >
            <Printer className="w-4 h-4" />
            <span>Generate Certified PDF</span>
          </button>
        </div>
      </div>

      {exportMessage && (
        <div className="p-3 bg-emerald-50 border border-emerald-300 rounded-xl text-xs font-semibold text-emerald-900 flex items-center gap-2">
          <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
          <span>{exportMessage}</span>
        </div>
      )}

      {/* Top Summary Metrics */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="p-4 bg-white border border-slate-200 rounded-xl shadow-2xs space-y-1">
          <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Total FIRs Logged</span>
          <p className="text-2xl font-bold text-slate-900">1,284</p>
          <span className="text-[11px] text-emerald-600 font-semibold flex items-center gap-1">
            <TrendingUp className="w-3.5 h-3.5" /> +12.4% vs prev quarter
          </span>
        </div>

        <div className="p-4 bg-white border border-slate-200 rounded-xl shadow-2xs space-y-1">
          <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Charge Sheet Filing Rate</span>
          <p className="text-2xl font-bold text-blue-700">89.4%</p>
          <span className="text-[11px] text-blue-600 font-medium">Sec 173 CrPC compliance</span>
        </div>

        <div className="p-4 bg-white border border-slate-200 rounded-xl shadow-2xs space-y-1">
          <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Avg Forensic Turnaround</span>
          <p className="text-2xl font-bold text-purple-700">11.2 <span className="text-xs font-normal text-slate-500">Days</span></p>
          <span className="text-[11px] text-purple-600 font-medium">FSL Kalina & Pune Hubs</span>
        </div>

        <div className="p-4 bg-white border border-slate-200 rounded-xl shadow-2xs space-y-1">
          <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Evidence Integrity Score</span>
          <p className="text-2xl font-bold text-emerald-700">100%</p>
          <span className="text-[11px] text-emerald-600 font-medium">Zero SHA-256 hash discrepancies</span>
        </div>
      </div>

      {/* Charts Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Crime Type Breakdown */}
        <div className="p-5 bg-white border border-slate-200 rounded-xl shadow-2xs space-y-4">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-sm font-bold text-slate-900">Cases by Crime Classification</h3>
              <p className="text-xs text-slate-500">Categorization under Indian Penal Code & Special Acts</p>
            </div>
            <span className="text-xs font-mono font-bold text-blue-700 bg-blue-50 px-2 py-0.5 rounded">
              YTD 2026
            </span>
          </div>

          <div className="h-64 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={CRIME_TYPE_DATA} margin={{ top: 10, right: 10, left: -20, bottom: 20 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
                <XAxis dataKey="name" tick={{ fontSize: 10 }} interval={0} angle={-15} textAnchor="end" />
                <YAxis tick={{ fontSize: 10 }} />
                <Tooltip />
                <Bar dataKey="cases" fill="#1e40af" radius={[4, 4, 0, 0]}>
                  {CRIME_TYPE_DATA.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.color} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Monthly Case Trend & Disposal */}
        <div className="p-5 bg-white border border-slate-200 rounded-xl shadow-2xs space-y-4">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-sm font-bold text-slate-900">Monthly Registration vs Clearance</h3>
              <p className="text-xs text-slate-500">6-Month trajectory of case registrations & charge sheets</p>
            </div>
            <span className="text-xs font-mono font-bold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded">
              Clearance 89%
            </span>
          </div>

          <div className="h-64 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={MONTHLY_TREND_DATA} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
                <XAxis dataKey="month" tick={{ fontSize: 11 }} />
                <YAxis tick={{ fontSize: 11 }} />
                <Tooltip />
                <Legend wrapperStyle={{ fontSize: '11px' }} />
                <Line type="monotone" dataKey="registered" stroke="#dc2626" strokeWidth={2} name="FIRs Logged" />
                <Line type="monotone" dataKey="chargeSheeted" stroke="#2563eb" strokeWidth={2} name="Charge Sheets Filed" />
                <Line type="monotone" dataKey="closed" stroke="#059669" strokeWidth={2} name="Judicially Disposed" />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* Station-by-Station Comparison Table */}
      <div className="p-5 bg-white border border-slate-200 rounded-xl shadow-2xs space-y-4">
        <div>
          <h3 className="text-sm font-bold text-slate-900">Sub-Divisional Station Performance Matrix</h3>
          <p className="text-xs text-slate-500">Comparative breakdown across Western Suburbs Zone II stations</p>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-xs text-left">
            <thead className="bg-slate-100 text-slate-700 uppercase font-mono text-[10px] tracking-wider">
              <tr>
                <th className="p-3">Police Station</th>
                <th className="p-3">Active Dockets</th>
                <th className="p-3">Charge Sheets / Closed</th>
                <th className="p-3">Pending FSL Lab</th>
                <th className="p-3">Disposal Efficiency</th>
                <th className="p-3">Status Rating</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200 text-slate-800">
              {STATION_PERFORMANCE_DATA.map((st, idx) => {
                const efficiency = Math.round((st.closed / (st.active + st.closed)) * 100);
                return (
                  <tr key={idx} className="hover:bg-slate-50 transition-colors">
                    <td className="p-3 font-bold text-slate-900">{st.station} Police Station</td>
                    <td className="p-3 font-mono font-semibold text-blue-700">{st.active}</td>
                    <td className="p-3 font-mono font-semibold text-emerald-700">{st.closed}</td>
                    <td className="p-3 font-mono font-semibold text-purple-700">{st.pendingFsl}</td>
                    <td className="p-3 font-mono font-bold text-slate-900">{efficiency}%</td>
                    <td className="p-3">
                      <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                        efficiency >= 70 ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-800'
                      }`}>
                        {efficiency >= 70 ? 'Optimal' : 'Supervision Needed'}
                      </span>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
