import 'dotenv/config';
process.env.NODE_ENV = 'test';
process.env.JWT_SECRET = process.env.JWT_SECRET || 'test-jwt-secret-maharashtra-police-2026';
import test from 'node:test';
import assert from 'node:assert';
import crypto from 'crypto';
import { OFFLINE_OFFICERS_ROSTER } from '../routes/officers';
import { antivirusService } from '../services/antivirusService';
import { encryptBuffer, decryptBuffer } from '../services/cryptoService';
import { OFFLINE_SAMPLE_CASES } from '../routes/cases';

test('Officers Management & Evidence File Upload Integration Suite', async (t) => {
  // 1. Officer Roster Resilience
  await t.test('1. Officers Roster: Clean roster supports dynamic officer enlistment in offline mode', () => {
    assert.ok(Array.isArray(OFFLINE_OFFICERS_ROSTER), 'Roster must be an array');
    
    // Verify dynamic addition and retrieval
    const customOfficer = {
      id: 'USR-TEST-001',
      badgeNo: 'MH-POL-9999',
      username: 'custom.officer@ecasevault.com',
      fullName: 'Custom Inspector',
      role: 'POLICE',
      station_id: 'ANDHERI-PS',
      status: 'ACTIVE',
    };
    OFFLINE_OFFICERS_ROSTER.push(customOfficer);
    const retrieved = OFFLINE_OFFICERS_ROSTER.find(o => o.badgeNo === 'MH-POL-9999');
    assert.ok(retrieved, 'Dynamically enlisted officer must be present');
    assert.strictEqual(retrieved.role, 'POLICE');
    assert.strictEqual(retrieved.station_id, 'ANDHERI-PS');
    // Clean up
    OFFLINE_OFFICERS_ROSTER.pop();
  });

  // 2. Member Auto-Generated Temporary Password
  await t.test('2. Member Provisioning: Auto-generates compliant password when omitted by UI', () => {
    const randomHex = crypto.randomBytes(4).toString('hex');
    const autoGeneratedPassword = `MhPolice#2026_${randomHex}`;

    assert.ok(autoGeneratedPassword.length >= 12, 'Auto-generated password must meet >= 12 character requirement');
    assert.ok(autoGeneratedPassword.startsWith('MhPolice#2026_'), 'Must use standardized state police prefix');
  });

  // 3. Evidence Upload Antivirus & Cryptographic Sealing
  await t.test('3. Evidence Upload: Clean file passes ClamAV scan and receives cryptographic seal', async () => {
    const evidenceContent = Buffer.from('OFFICIAL EVIDENCE: Seized hard disk sector image partition 1 forensic extraction log');
    const scanResult = await antivirusService.scanBuffer(evidenceContent, 'evidence_dump.raw');

    assert.strictEqual(scanResult.isClean, true, 'Benign forensic extraction must pass antivirus scan');
    assert.strictEqual(scanResult.isInfected, false, 'Clean file must not be flagged as infected');

    // SHA-256 digest sealing
    const calculatedHash = crypto.createHash('sha256').update(evidenceContent).digest('hex');
    assert.strictEqual(calculatedHash.length, 64, 'SHA-256 digest must be 64 characters hex');

    // AES-256-GCM encryption
    const encrypted = encryptBuffer(evidenceContent);
    assert.ok(encrypted.encryptedData.length > 0);
    assert.strictEqual(encrypted.ivHex.length, 32, 'AES-256-GCM requires 16-byte (32 hex) IV');
    assert.strictEqual(encrypted.authTagHex.length, 32, 'AES-256-GCM requires 16-byte (32 hex) auth tag');

    const decrypted = decryptBuffer(
      encrypted.encryptedData,
      encrypted.saltHex,
      encrypted.ivHex,
      encrypted.authTagHex
    );
    assert.strictEqual(decrypted.toString(), evidenceContent.toString(), 'Decrypted evidence must match original exactly');
  });

  // 4. Evidence Upload Antivirus Quarantine Rejection
  await t.test('4. Evidence Upload: Malicious executable or malware signature is detected and quarantined', async () => {
    const eicarSignature = Buffer.from('X5O!P%@AP[4\\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*');
    const scanResult = await antivirusService.scanBuffer(eicarSignature, 'suspicious_payload.exe');

    assert.strictEqual(scanResult.isClean, false, 'EICAR virus signature must be flagged');
    assert.strictEqual(scanResult.isInfected, true, 'Malware must be flagged as infected');
    assert.ok(scanResult.threatName, 'Threat name must be identified');
  });

  // 5. Offline FIR Case Creation Resilience
  await t.test('5. Case Creation: Registers case with attached hard copy FIR scan without DB crashes', () => {
    const mockFirScanFile = {
      name: 'signed_fir_scan_04821.jpg',
      size: 1048576, // 1MB
      type: 'image/jpeg'
    };

    const caseId = `MH-MUM-2026-${crypto.randomUUID().substring(0, 8).toUpperCase()}`;
    const firDocId = `DOC-SCAN-${caseId.slice(-5)}`;
    const evdId = `EVD-FIR-${Date.now().toString().slice(-6)}`;

    // Verify document record structure
    const docRecord = {
      id: firDocId,
      docNumber: `SCAN-FIR-${caseId.slice(-5)}`,
      caseId,
      title: `Scanned Physical FIR (${mockFirScanFile.name})`,
      type: 'EVIDENCE_RECORD' as const,
      department: 'POLICE_INVESTIGATION' as const,
      clearance: 'CONFIDENTIAL' as const,
      attachmentsCount: 1
    };

    assert.strictEqual(docRecord.type, 'EVIDENCE_RECORD');
    assert.strictEqual(docRecord.attachmentsCount, 1);

    // Verify evidence item record structure
    const evidenceRecord = {
      id: evdId,
      caseId,
      evidenceTag: `EV-MH-2026-${Date.now().toString().slice(-6)}`,
      category: 'Documentary Evidence' as const,
      description: `Physical Hard Copy FIR Scan: ${mockFirScanFile.name}`,
      status: 'Malkhana Storage' as const,
      isIntegrityVerified: true
    };

    assert.strictEqual(evidenceRecord.category, 'Documentary Evidence');
    assert.strictEqual(evidenceRecord.status, 'Malkhana Storage');
    assert.strictEqual(evidenceRecord.isIntegrityVerified, true);
  });
});
